import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget42.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedParaprimaryleftWidget108.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedNavheaderWidget10.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedParaprimaryleftWidget112.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedBackgroundWidget6.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedFrame35Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedFrame34Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedGroup280Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedIphoneBarWidget23.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsupdatesystemtaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget41.dart';

/* Frame Settings Update System - Task Management
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsUpdateSystemTaskManagementWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 0, 110, 233),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 668.0,
                child: GeneratedBackgroundWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 42.0,
                child: GeneratedNavheaderWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedButtonprimarydefaultWidget41(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget23(),
              ),
              Positioned(
                left: 15.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 103.00000762939453,
                child: GeneratedGroup280Widget(),
              ),
              Positioned(
                left: 97.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 22.0,
                child: GeneratedParaprimaryleftWidget108(),
              ),
              Positioned(
                left: 94.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 15.0,
                child: GeneratedFrame34Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 571.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 50.0,
                child: GeneratedButtonprimarydefaultWidget42(),
              ),
              Positioned(
                left: 0.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 20.0,
                child: GeneratedParaprimaryleftWidget112(),
              ),
              Positioned(
                left: 0.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 30.0,
                child: GeneratedFrame35Widget(),
              )
            ]),
      ),
    ));
  }
}
