import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedParaprimarycenterWidget4.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedIphoneBarWidget3.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedParaprimarycenterWidget2.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedParaprimarycenterWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedButtonprimarydefaultWidget1.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedParaprimarycenterWidget3.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedParaprimarycenterWidget1.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedButtonprimarydefaultWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedRadiographicAIScanAppWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedInputprimarydefaultWidget1.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedInputprimarydefaultWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedsigninwidget/generated/GeneratedForgotpasswordWidget.dart';

/* Frame sign in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget3(),
              ),
              Positioned(
                left: 15.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 94.0,
                child: GeneratedParaprimarycenterWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 94.0,
                child: GeneratedParaprimarycenterWidget1(),
              ),
              Positioned(
                left: 73.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 24.0,
                child: GeneratedRadiographicAIScanAppWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 40.0,
                child: GeneratedParaprimarycenterWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 38.0,
                child: GeneratedParaprimarycenterWidget3(),
              ),
              Positioned(
                left: 126.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 20.0,
                child: GeneratedParaprimarycenterWidget4(),
              ),
              Positioned(
                left: 15.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 50.0,
                child: GeneratedButtonprimarydefaultWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 345.0000915527344,
                height: 48.0,
                child: GeneratedInputprimarydefaultWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 48.0,
                child: GeneratedInputprimarydefaultWidget1(),
              ),
              Positioned(
                left: 268.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 17.0,
                child: GeneratedForgotpasswordWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 82.0509033203125,
                child: GeneratedButtonprimarydefaultWidget1(),
              )
            ]),
      ),
    ));
  }
}
