import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedF4F9FFWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedB8D9FFWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedA4A4A4Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedColorUsageWidget1.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/Generated3A97FEWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/Generated006EE9Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/Generated97C8FFWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedDestructiveColorWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedC6C2C2Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedCB2F2FWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedTextColorWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/Generated5AA8FFWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/Generated105CDBWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/Generated7CBAFFWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedFFFFFFWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/Generated000000Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse15Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedBrandColorWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/Generated1A81F4Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedD6E9FFWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcolorusagewidget/generated/GeneratedEllipse6Widget.dart';

/* Frame Color Usage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedColorUsageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 826.0,
        height: 696.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 239, 246, 255),
                ),
              ),
              Positioned(
                left: 36.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 47.0,
                child: GeneratedColorUsageWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 25.0,
                child: GeneratedBrandColorWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 25.0,
                child: GeneratedTextColorWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 25.0,
                child: GeneratedDestructiveColorWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 19.0,
                child: Generated105CDBWidget(),
              ),
              Positioned(
                left: 124.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 19.0,
                child: Generated006EE9Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 19.0,
                child: Generated1A81F4Widget(),
              ),
              Positioned(
                left: 252.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 19.0,
                child: Generated3A97FEWidget(),
              ),
              Positioned(
                left: 315.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 19.0,
                child: Generated5AA8FFWidget(),
              ),
              Positioned(
                left: 379.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 19.0,
                child: Generated7CBAFFWidget(),
              ),
              Positioned(
                left: 443.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 19.0,
                child: Generated97C8FFWidget(),
              ),
              Positioned(
                left: 507.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 19.0,
                child: GeneratedB8D9FFWidget(),
              ),
              Positioned(
                left: 572.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 19.0,
                child: GeneratedD6E9FFWidget(),
              ),
              Positioned(
                left: 637.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 19.0,
                child: GeneratedF4F9FFWidget(),
              ),
              Positioned(
                left: 703.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 19.0,
                child: GeneratedFFFFFFWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 164.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 228.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 19.0,
                child: Generated000000Widget(),
              ),
              Positioned(
                left: 122.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 19.0,
                child: GeneratedA4A4A4Widget(),
              ),
              Positioned(
                left: 184.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 19.0,
                child: GeneratedC6C2C2Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 647.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 19.0,
                child: GeneratedCB2F2FWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse15Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse13Widget(),
              ),
              Positioned(
                left: 164.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse14Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 356.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 420.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse7Widget(),
              ),
              Positioned(
                left: 484.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 548.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 612.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 676.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse11Widget(),
              )
            ]),
      ),
    ));
  }
}
