import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFontWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFrame1875Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFrame1873Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFrame1872Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFrame1869Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFrame1876Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFrame1870Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFontFamilyPoppinsJenisRegularWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFrame1871Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedfontstylewidget/generated/GeneratedFrame1874Widget.dart';

/* Frame Font Style
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFontStyleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1111.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1400.0,
                      height: 1111.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 239, 246, 255),
                              ),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 724.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 15.0,
                              child: GeneratedFrame1876Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 678.0,
                              right: null,
                              bottom: null,
                              width: 358.0,
                              height: 18.0,
                              child: GeneratedFrame1875Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 626.0,
                              right: null,
                              bottom: null,
                              width: 405.0,
                              height: 20.0,
                              child: GeneratedFrame1874Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 572.0,
                              right: null,
                              bottom: null,
                              width: 449.0,
                              height: 22.0,
                              child: GeneratedFrame1873Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 512.0,
                              right: null,
                              bottom: null,
                              width: 540.0,
                              height: 28.0,
                              child: GeneratedFrame1872Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 451.0,
                              right: null,
                              bottom: null,
                              width: 627.0,
                              height: 29.0,
                              child: GeneratedFrame1871Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 381.0,
                              right: null,
                              bottom: null,
                              width: 803.0,
                              height: 38.0,
                              child: GeneratedFrame1870Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 978.0,
                              height: 44.0,
                              child: GeneratedFrame1869Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 26.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 50.0,
                              child: GeneratedFontWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 48.0,
                              child:
                                  GeneratedFontFamilyPoppinsJenisRegularWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
