import 'package:flutter/material.dart';

/* Frame check
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 25.0,
        height: 25.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(0, 0, 0, 0),
          ),
        ),
      ),
    ));
  }
}
