import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedframe85widget/generated/GeneratedFrame84Widget.dart';

/* Frame Frame 85
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame85Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedGroup298Widget'),
      child: Container(
        width: 375.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 800.0,
                child: GeneratedFrame84Widget(),
              )
            ]),
      ),
    ));
  }
}
