import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedText2xssemiboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedTextlgsemiboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedText2xlsemiboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedGroup278Widget9.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedFontFamilyPoppinsJenisRegularWidget3.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedText3xlsemiboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedTextbasesemiboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedTextsmsemiboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedTextxlsemiboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedFontWidget3.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographysemiboldwidget/generated/GeneratedTextxssemiboldWidget.dart';

/* Frame Tipography SemiBold
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTipographySemiBoldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1111.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1400.0,
                      height: 1111.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 239, 246, 255),
                              ),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 741.0,
                              right: null,
                              bottom: null,
                              width: 227.0,
                              height: 17.0,
                              child: GeneratedText2xssemiboldWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 694.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 20.0,
                              child: GeneratedTextxssemiboldWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 642.0,
                              right: null,
                              bottom: null,
                              width: 317.0,
                              height: 22.0,
                              child: GeneratedTextsmsemiboldWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 362.0,
                              height: 24.0,
                              child: GeneratedTextbasesemiboldWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 528.0,
                              right: null,
                              bottom: null,
                              width: 452.0,
                              height: 30.0,
                              child: GeneratedTextlgsemiboldWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 542.0,
                              height: 31.0,
                              child: GeneratedTextxlsemiboldWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 397.0,
                              right: null,
                              bottom: null,
                              width: 722.0,
                              height: 40.0,
                              child: GeneratedText2xlsemiboldWidget(),
                            ),
                            Positioned(
                              left: 182.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 422.0,
                              child: GeneratedGroup278Widget9(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 902.0,
                              height: 46.0,
                              child: GeneratedText3xlsemiboldWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 26.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 50.0,
                              child: GeneratedFontWidget3(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 48.0,
                              child:
                                  GeneratedFontFamilyPoppinsJenisRegularWidget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
