description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Righteous"
      fonts: 
        - 
          asset: "fonts/Righteous-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Poppins-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Poppins-500italic.ttf"
          style: "italic"
          weight: 500
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Actor"
      fonts: 
        - 
          asset: "fonts/Actor-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
