import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame68Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame73Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame67Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame74Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame75Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame71Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame70Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame69Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedEllipse255Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedcalendarwidget4/generated/GeneratedFrame72Widget.dart';

/* Frame Calendar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendarWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 0, 110, 233),
            offset: Offset(1.0, 2.0),
            blurRadius: 6.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          width: 315.0,
          height: 298.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(20.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 56.0,
                  top: 210.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedEllipse255Widget(),
                ),
                Positioned(
                  left: 61.0,
                  top: 27.0,
                  right: null,
                  bottom: null,
                  width: 193.0,
                  height: 24.0,
                  child: GeneratedFrame75Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 80.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 18.0,
                  child: GeneratedFrame67Widget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 115.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 146.0,
                  child: GeneratedFrame68Widget(),
                ),
                Positioned(
                  left: 61.0,
                  top: 115.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 150.0,
                  child: GeneratedFrame69Widget(),
                ),
                Positioned(
                  left: 102.0,
                  top: 115.0,
                  right: null,
                  bottom: null,
                  width: 14.0,
                  height: 150.0,
                  child: GeneratedFrame70Widget(),
                ),
                Positioned(
                  left: 147.0,
                  top: 115.0,
                  right: null,
                  bottom: null,
                  width: 14.0,
                  height: 150.0,
                  child: GeneratedFrame71Widget(),
                ),
                Positioned(
                  left: 196.0,
                  top: 115.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 150.0,
                  child: GeneratedFrame72Widget(),
                ),
                Positioned(
                  left: 237.0,
                  top: 115.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 150.0,
                  child: GeneratedFrame73Widget(),
                ),
                Positioned(
                  left: 278.0,
                  top: 115.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 150.0,
                  child: GeneratedFrame74Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
