import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget32.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget34.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget31.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget33.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget35.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedButtonprimaryfillWidget2.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedIphoneBarWidget17.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget30.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedNavheaderWidget6.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingstaskmanagementwidget/generated/GeneratedBackgroundWidget2.dart';

/* Frame Settings - Task Management
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsTaskManagementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 0, 110, 233),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 668.0,
                child: GeneratedBackgroundWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 42.0,
                child: GeneratedNavheaderWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedButtonprimarydefaultWidget30(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget31(),
              ),
              Positioned(
                left: 0.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimaryfillWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget32(),
              ),
              Positioned(
                left: 0.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget33(),
              ),
              Positioned(
                left: 0.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget34(),
              ),
              Positioned(
                left: 0.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget35(),
              )
            ]),
      ),
    ));
  }
}
