import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedCTScanWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedRectangle600Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedNavigationBarWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedProfileWidget3.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedButtonprimarydefaultWidget10.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedXRayWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedIMG20201201WA0022_21Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedInsertimageWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedEllipse257Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedRectangle598Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedNavheaderWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedIphoneBarWidget5.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedSubtractWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget/generated/GeneratedRectangle599Widget.dart';

/* Frame Profile - Task Mangement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileTaskMangementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedInsertscanWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(33.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(33.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(33.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 375.0,
                  top: 221.91073608398438,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 221.91091918945312,
                  child: GeneratedSubtractWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedIphoneBarWidget5(),
                ),
                Positioned(
                  left: 11.0,
                  top: 69.0,
                  right: null,
                  bottom: null,
                  width: 345.0,
                  height: 42.0,
                  child: GeneratedNavheaderWidget(),
                ),
                Positioned(
                  left: -1.0,
                  top: 732.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 80.0,
                  child: GeneratedNavigationBarWidget(),
                ),
                Positioned(
                  left: -1.0,
                  top: 188.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 174.0,
                  child: GeneratedProfileWidget3(),
                ),
                Positioned(
                  left: -124.0,
                  top: 73.0,
                  right: null,
                  bottom: null,
                  width: 720.0,
                  height: 1080.0,
                  child: GeneratedIMG20201201WA0022_21Widget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 422.0,
                  right: null,
                  bottom: null,
                  width: 334.0,
                  height: 48.0,
                  child: GeneratedButtonprimarydefaultWidget10(),
                ),
                Positioned(
                  left: 78.0,
                  top: 539.0,
                  right: null,
                  bottom: null,
                  width: 218.0,
                  height: 31.0,
                  child: GeneratedRectangle598Widget(),
                ),
                Positioned(
                  left: 141.0,
                  top: 545.0,
                  right: null,
                  bottom: null,
                  width: 93.0,
                  height: 20.0,
                  child: GeneratedInsertimageWidget(),
                ),
                Positioned(
                  left: 15.0,
                  top: 670.0,
                  right: null,
                  bottom: null,
                  width: 141.0,
                  height: 31.0,
                  child: GeneratedRectangle599Widget(),
                ),
                Positioned(
                  left: 222.0,
                  top: 670.0,
                  right: null,
                  bottom: null,
                  width: 138.0,
                  height: 31.0,
                  child: GeneratedRectangle600Widget(),
                ),
                Positioned(
                  left: 49.0,
                  top: 678.0,
                  right: null,
                  bottom: null,
                  width: 54.0,
                  height: 20.0,
                  child: GeneratedXRayWidget(),
                ),
                Positioned(
                  left: 256.0,
                  top: 678.0,
                  right: null,
                  bottom: null,
                  width: 74.0,
                  height: 20.0,
                  child: GeneratedCTScanWidget(),
                ),
                Positioned(
                  left: 136.0,
                  top: 136.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 112.0,
                  child: GeneratedEllipse257Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
