import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedOrdraganddropfileWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedParaprimarycenterWidget19.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedRadiographicAIScanAppWidget3.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedButtonprimarydefaultWidget13.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedButtonprimarydefaultWidget14.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedRectangle607Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedBrowseWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedIphoneBarWidget7.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedInputprimarydefaultWidget8.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedRectangle606Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedinsertscanwidget/generated/GeneratedInputprimarydefaultWidget9.dart';

/* Frame insert scan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInsertscanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedResultWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(33.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(33.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(33.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedIphoneBarWidget7(),
                ),
                Positioned(
                  left: 20.0,
                  top: 104.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 57.0,
                  child: GeneratedParaprimarycenterWidget19(),
                ),
                Positioned(
                  left: 20.0,
                  top: 69.0,
                  right: null,
                  bottom: null,
                  width: 36.0,
                  height: 36.0,
                  child: GeneratedButtonprimarydefaultWidget13(),
                ),
                Positioned(
                  left: 15.0,
                  top: 680.0,
                  right: null,
                  bottom: null,
                  width: 345.0,
                  height: 50.0,
                  child: GeneratedButtonprimarydefaultWidget14(),
                ),
                Positioned(
                  left: 74.0,
                  top: 161.0,
                  right: null,
                  bottom: null,
                  width: 217.0,
                  height: 24.0,
                  child: GeneratedRadiographicAIScanAppWidget3(),
                ),
                Positioned(
                  left: 63.0,
                  top: 391.0,
                  right: null,
                  bottom: null,
                  width: 250.0,
                  height: 250.0,
                  child: GeneratedRectangle606Widget(),
                ),
                Positioned(
                  left: 124.0,
                  top: 544.0,
                  right: null,
                  bottom: null,
                  width: 118.0,
                  height: 29.0,
                  child: GeneratedRectangle607Widget(),
                ),
                Positioned(
                  left: 157.0,
                  top: 549.0,
                  right: null,
                  bottom: null,
                  width: 49.0,
                  height: 23.0,
                  child: GeneratedBrowseWidget(),
                ),
                Positioned(
                  left: 116.0,
                  top: 598.0,
                  right: null,
                  bottom: null,
                  width: 128.0,
                  height: 20.0,
                  child: GeneratedOrdraganddropfileWidget(),
                ),
                Positioned(
                  left: 9.0,
                  top: 206.0,
                  right: null,
                  bottom: null,
                  width: 345.0000915527344,
                  height: 48.0,
                  child: GeneratedInputprimarydefaultWidget8(),
                ),
                Positioned(
                  left: 9.0,
                  top: 298.0,
                  right: null,
                  bottom: null,
                  width: 345.0000915527344,
                  height: 48.0,
                  child: GeneratedInputprimarydefaultWidget9(),
                )
              ]),
        ),
      ),
    ));
  }
}
