import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedIphoneBarWidget19.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget92.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget87.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget101.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedCloseSquareWidget2.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget93.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget91.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget96.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget100.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget85.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget90.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget94.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget97.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget89.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget86.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget98.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget95.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget88.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingsnotificationtaskmanagementwidget1/generated/GeneratedParaprimaryleftWidget99.dart';

/* Frame Settings Notification - Task Management
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsNotificationTaskManagementWidget1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 20.0,
                child: GeneratedParaprimaryleftWidget85(),
              ),
              Positioned(
                left: 0.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget86(),
              ),
              Positioned(
                left: 0.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget87(),
              ),
              Positioned(
                left: 0.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget88(),
              ),
              Positioned(
                left: 0.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget89(),
              ),
              Positioned(
                left: 0.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget90(),
              ),
              Positioned(
                left: 0.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget91(),
              ),
              Positioned(
                left: 0.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget92(),
              ),
              Positioned(
                left: 0.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget93(),
              ),
              Positioned(
                left: 0.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget94(),
              ),
              Positioned(
                left: 0.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget95(),
              ),
              Positioned(
                left: 0.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget96(),
              ),
              Positioned(
                left: 0.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget97(),
              ),
              Positioned(
                left: 0.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget98(),
              ),
              Positioned(
                left: 0.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget99(),
              ),
              Positioned(
                left: 0.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget100(),
              ),
              Positioned(
                left: 0.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 38.0,
                child: GeneratedParaprimaryleftWidget101(),
              ),
              Positioned(
                left: 327.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedCloseSquareWidget2(),
              )
            ]),
      ),
    ));
  }
}
