import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedButtonprimarydefaultWidget17.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedEllipse258Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedSubtractWidget1.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedProfileWidget7.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedNavheaderWidget2.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedButtonprimarydefaultWidget18.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedButtonprimarydefaultWidget19.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedNavigationBarWidget2.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedIphoneBarWidget13.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedIMG20201201WA0022_21Widget1.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedNotifprimarydefaultWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedButtonprimarydefaultWidget20.dart';
import 'package:flutterapp/deepbreathapp/generatedprofiletaskmangementwidget1/generated/GeneratedButtonprimaryfillWidget.dart';

/* Frame Profile - Task Mangement
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileTaskMangementWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 375.0,
                top: 221.91073608398438,
                right: null,
                bottom: null,
                width: 375.0,
                height: 221.91091918945312,
                child: GeneratedSubtractWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget13(),
              ),
              Positioned(
                left: 15.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 42.0,
                child: GeneratedNavheaderWidget2(),
              ),
              Positioned(
                left: -1.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 80.0,
                child: GeneratedNavigationBarWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimaryfillWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedButtonprimarydefaultWidget20(),
              ),
              Positioned(
                left: 259.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifprimarydefaultWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 174.0,
                child: GeneratedProfileWidget7(),
              ),
              Positioned(
                left: -124.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 720.0,
                height: 1080.0,
                child: GeneratedIMG20201201WA0022_21Widget1(),
              ),
              Positioned(
                left: 125.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 112.0,
                child: GeneratedEllipse258Widget(),
              )
            ]),
      ),
    ));
  }
}
