import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedlocationtaskmanagementwidget/generated/GeneratedGroup274Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedlocationtaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget43.dart';
import 'package:flutterapp/deepbreathapp/generatedlocationtaskmanagementwidget/generated/GeneratedIphoneBarWidget24.dart';
import 'package:flutterapp/deepbreathapp/generatedlocationtaskmanagementwidget/generated/GeneratedMaskgroupWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedlocationtaskmanagementwidget/generated/GeneratedNavheaderWidget11.dart';
import 'package:flutterapp/deepbreathapp/generatedlocationtaskmanagementwidget/generated/GeneratedFrame76Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedlocationtaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget44.dart';

/* Frame Location - Task Management
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLocationTaskManagementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 0, 110, 233),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 668.0,
                child: GeneratedFrame76Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 42.0,
                child: GeneratedNavheaderWidget11(),
              ),
              Positioned(
                left: 20.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedButtonprimarydefaultWidget43(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget24(),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 668.0,
                child: GeneratedMaskgroupWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 689.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 91.0,
                child: GeneratedGroup274Widget(),
              ),
              Positioned(
                left: 305.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedButtonprimarydefaultWidget44(),
              )
            ]),
      ),
    ));
  }
}
