import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedTextlgmediumWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedText3xlmediumWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedTextxsmediumWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedTextbasemediumWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedGroup278Widget8.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedFontFamilyPoppinsJenisRegularWidget2.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedText2xlmediumWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedTextxlmediumWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedFontWidget2.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedText2xsmediumWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographymediumwidget/generated/GeneratedTextsmmediumWidget.dart';

/* Frame Tipography Medium
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTipographyMediumWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1111.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1400.0,
                      height: 1111.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 239, 246, 255),
                              ),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 741.0,
                              right: null,
                              bottom: null,
                              width: 226.0,
                              height: 17.0,
                              child: GeneratedText2xsmediumWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 694.0,
                              right: null,
                              bottom: null,
                              width: 270.0,
                              height: 20.0,
                              child: GeneratedTextxsmediumWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 642.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 22.0,
                              child: GeneratedTextsmmediumWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 359.0,
                              height: 24.0,
                              child: GeneratedTextbasemediumWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 528.0,
                              right: null,
                              bottom: null,
                              width: 449.0,
                              height: 30.0,
                              child: GeneratedTextlgmediumWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 538.0,
                              height: 31.0,
                              child: GeneratedTextxlmediumWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 397.0,
                              right: null,
                              bottom: null,
                              width: 716.0,
                              height: 40.0,
                              child: GeneratedText2xlmediumWidget(),
                            ),
                            Positioned(
                              left: 182.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 422.0,
                              child: GeneratedGroup278Widget8(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 895.0,
                              height: 46.0,
                              child: GeneratedText3xlmediumWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 26.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 50.0,
                              child: GeneratedFontWidget2(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 48.0,
                              child:
                                  GeneratedFontFamilyPoppinsJenisRegularWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
