import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedframe87widget/generated/GeneratedProfileTaskMangementWidget2.dart';

/* Frame Frame 87
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame87Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 812.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 812.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 812.0,
                              child: GeneratedProfileTaskMangementWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
