import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget27.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedCategoryWidget3.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedNavheaderWidget4.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedInputprimarydefaultWidget10.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedInputprimarydefaultWidget12.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedCategoryWidget5.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedCategoryWidget2.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget26.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedInputprimarydefaultWidget11.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedCategoryWidget4.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedIphoneBarWidget15.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedInputprimarydefaultWidget13.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedBackgroundWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedEllipse259Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedmyprofiletaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget25.dart';

/* Frame My Profile - Task Management
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMyProfileTaskManagementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedProfileTaskMangementWidget1'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(33.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(33.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(33.0),
                  child: Container(
                    color: Color.fromARGB(255, 0, 110, 233),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 144.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 668.0,
                  child: GeneratedBackgroundWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 63.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 42.0,
                  child: GeneratedNavheaderWidget4(),
                ),
                Positioned(
                  left: 20.0,
                  top: 66.0,
                  right: null,
                  bottom: null,
                  width: 36.0,
                  height: 36.0,
                  child: GeneratedButtonprimarydefaultWidget25(),
                ),
                Positioned(
                  left: 20.0,
                  top: 287.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 30.0,
                  child: GeneratedCategoryWidget2(),
                ),
                Positioned(
                  left: 20.0,
                  top: 317.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 48.0,
                  child: GeneratedInputprimarydefaultWidget10(),
                ),
                Positioned(
                  left: 20.0,
                  top: 385.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 30.0,
                  child: GeneratedCategoryWidget3(),
                ),
                Positioned(
                  left: 20.0,
                  top: 483.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 30.0,
                  child: GeneratedCategoryWidget4(),
                ),
                Positioned(
                  left: 20.0,
                  top: 581.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 30.0,
                  child: GeneratedCategoryWidget5(),
                ),
                Positioned(
                  left: 20.0,
                  top: 415.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 48.0,
                  child: GeneratedInputprimarydefaultWidget11(),
                ),
                Positioned(
                  left: 20.0,
                  top: 611.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 48.0,
                  child: GeneratedInputprimarydefaultWidget12(),
                ),
                Positioned(
                  left: 21.0,
                  top: 714.0,
                  right: null,
                  bottom: null,
                  width: 334.0,
                  height: 48.0,
                  child: GeneratedButtonprimarydefaultWidget26(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedIphoneBarWidget15(),
                ),
                Positioned(
                  left: 200.0,
                  top: 238.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedButtonprimarydefaultWidget27(),
                ),
                Positioned(
                  left: 20.0,
                  top: 513.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 48.0,
                  child: GeneratedInputprimarydefaultWidget13(),
                ),
                Positioned(
                  left: 124.0,
                  top: 155.0,
                  right: null,
                  bottom: null,
                  width: 112.0,
                  height: 112.0,
                  child: GeneratedEllipse259Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
