import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedText2xsboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedTextlgboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedTextbaseboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedFontFamilyPoppinsJenisRegularWidget4.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedText3xlboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedTextxlboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedTextsmboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedTextxsboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedGroup278Widget10.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedText2xlboldWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyboldwidget/generated/GeneratedFontWidget4.dart';

/* Frame Tipography Bold
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTipographyBoldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1111.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1400.0,
                      height: 1111.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 239, 246, 255),
                              ),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 741.0,
                              right: null,
                              bottom: null,
                              width: 229.0,
                              height: 17.0,
                              child: GeneratedText2xsboldWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 694.0,
                              right: null,
                              bottom: null,
                              width: 275.0,
                              height: 20.0,
                              child: GeneratedTextxsboldWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 642.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 22.0,
                              child: GeneratedTextsmboldWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 24.0,
                              child: GeneratedTextbaseboldWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 528.0,
                              right: null,
                              bottom: null,
                              width: 456.0,
                              height: 30.0,
                              child: GeneratedTextlgboldWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 547.0,
                              height: 31.0,
                              child: GeneratedTextxlboldWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 397.0,
                              right: null,
                              bottom: null,
                              width: 728.0,
                              height: 40.0,
                              child: GeneratedText2xlboldWidget(),
                            ),
                            Positioned(
                              left: 182.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 422.0,
                              child: GeneratedGroup278Widget10(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 910.0,
                              height: 46.0,
                              child: GeneratedText3xlboldWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 26.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 50.0,
                              child: GeneratedFontWidget4(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 48.0,
                              child:
                                  GeneratedFontFamilyPoppinsJenisRegularWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
