import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingshelptaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget39.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingshelptaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget40.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingshelptaskmanagementwidget/generated/GeneratedIphoneBarWidget22.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingshelptaskmanagementwidget/generated/GeneratedBackgroundWidget5.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingshelptaskmanagementwidget/generated/GeneratedInputprimarydefaultWidget17.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingshelptaskmanagementwidget/generated/GeneratedParaprimaryleftWidget107.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingshelptaskmanagementwidget/generated/GeneratedNavheaderWidget9.dart';

/* Frame Settings Help - Task Management
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsHelpTaskManagementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 0, 110, 233),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 668.0,
                child: GeneratedBackgroundWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 42.0,
                child: GeneratedNavheaderWidget9(),
              ),
              Positioned(
                left: 20.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedButtonprimarydefaultWidget39(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget22(),
              ),
              Positioned(
                left: 0.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 20.0,
                child: GeneratedParaprimaryleftWidget107(),
              ),
              Positioned(
                left: 15.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 228.0,
                child: GeneratedInputprimarydefaultWidget17(),
              ),
              Positioned(
                left: 15.0,
                top: 483.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 50.0,
                child: GeneratedButtonprimarydefaultWidget40(),
              )
            ]),
      ),
    ));
  }
}
