import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedgroup299widget/generated/GeneratedSplashScreenTaskMangementWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedgroup299widget/generated/GeneratedDeepBreathAIPoweredRadiographicScanWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component Group 299
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup299Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFrame85Widget'),
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSplashScreenTaskMangementWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7253333333333334;

                  final double height =
                      constraints.maxHeight * 0.06773399014778325;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14133333333333334,
                        y: constraints.maxHeight * 0.4876847290640394,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedDeepBreathAIPoweredRadiographicScanWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
