import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedTextlgregulerWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedTextxsregulerWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedText2xlregulerWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedGroup278Widget7.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedTextbaseregulerWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedFontFamilyPoppinsJenisRegularWidget1.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedTextxlregulerWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedText2xsregulerWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedText3xlregulerWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedTextsmregulerWidget.dart';
import 'package:flutterapp/deepbreathapp/generatedtipographyregulerwidget/generated/GeneratedFontWidget1.dart';

/* Frame Tipography Reguler
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTipographyRegulerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1111.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1400.0,
                      height: 1111.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 239, 246, 255),
                              ),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 741.0,
                              right: null,
                              bottom: null,
                              width: 223.0,
                              height: 17.0,
                              child: GeneratedText2xsregulerWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 694.0,
                              right: null,
                              bottom: null,
                              width: 267.0,
                              height: 20.0,
                              child: GeneratedTextxsregulerWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 642.0,
                              right: null,
                              bottom: null,
                              width: 312.0,
                              height: 22.0,
                              child: GeneratedTextsmregulerWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 356.0,
                              height: 24.0,
                              child: GeneratedTextbaseregulerWidget(),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 528.0,
                              right: null,
                              bottom: null,
                              width: 444.0,
                              height: 30.0,
                              child: GeneratedTextlgregulerWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 532.0,
                              height: 31.0,
                              child: GeneratedTextxlregulerWidget(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 397.0,
                              right: null,
                              bottom: null,
                              width: 709.0,
                              height: 40.0,
                              child: GeneratedText2xlregulerWidget(),
                            ),
                            Positioned(
                              left: 182.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 422.0,
                              child: GeneratedGroup278Widget7(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 886.0,
                              height: 46.0,
                              child: GeneratedText3xlregulerWidget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 26.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 50.0,
                              child: GeneratedFontWidget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 161.0,
                              height: 48.0,
                              child:
                                  GeneratedFontFamilyPoppinsJenisRegularWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
