import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedstatistictaskmanagementwidget/generated/GeneratedFrame61Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedstatistictaskmanagementwidget/generated/GeneratedIphoneBarWidget16.dart';

/* Frame Statistic - Task Management
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStatisticTaskManagementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 0, 110, 233),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 723.0,
                child: GeneratedFrame61Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget16(),
              )
            ]),
      ),
    ));
  }
}
