import 'package:flutter/material.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedFrame9Widget.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedInputprimarydefaultWidget15.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedIphoneBarWidget21.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedParaprimaryleftWidget104.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget38.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedNavheaderWidget8.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedParaprimaryleftWidget103.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedButtonprimarydefaultWidget37.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedInputprimarydefaultWidget14.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedBackgroundWidget4.dart';
import 'package:flutterapp/deepbreathapp/generatedsettingssecuritytaskmanagementwidget/generated/GeneratedInputprimarydefaultWidget16.dart';

/* Frame Settings Security - Task Management
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingsSecurityTaskManagementWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(33.0),
                child: Container(
                  color: Color.fromARGB(255, 0, 110, 233),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 668.0,
                child: GeneratedBackgroundWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 42.0,
                child: GeneratedNavheaderWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedButtonprimarydefaultWidget37(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIphoneBarWidget21(),
              ),
              Positioned(
                left: 0.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 20.0,
                child: GeneratedParaprimaryleftWidget103(),
              ),
              Positioned(
                left: 0.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 20.0,
                child: GeneratedParaprimaryleftWidget104(),
              ),
              Positioned(
                left: 15.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 48.0,
                child: GeneratedInputprimarydefaultWidget14(),
              ),
              Positioned(
                left: 15.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 48.0,
                child: GeneratedInputprimarydefaultWidget15(),
              ),
              Positioned(
                left: 15.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 48.0,
                child: GeneratedInputprimarydefaultWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 33.0,
                child: GeneratedFrame9Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 50.0,
                child: GeneratedButtonprimarydefaultWidget38(),
              )
            ]),
      ),
    ));
  }
}
